In [39]:
import importlib
import timeSeriesABC
import Timeseries
import ArrayTimeSeries
import StorageManager
import SMTimeSeries
importlib.reload(timeSeriesABC)
importlib.reload(Timeseries)
importlib.reload(ArrayTimeSeries)
importlib.reload(StorageManager)
importlib.reload(SMTimeSeries)

from ArrayTimeSeries import ArrayTimeSeries as ats
from Timeseries import TimeSeries as lts
from SMTimeSeries import SMTimeSeries as smts

import numpy as np
import os

In [40]:
a = lts(np.empty(3)*np.nan)

In [41]:
sm = StorageManager.FileStorageManager()

In [42]:
ts = SMTimeSeries.SMTimeSeries(range(10),range(10),SM=sm,id=12)

In [43]:
smts(times=range(5),values=range(5),SM=None)

SMTimeSeries(Length: 5, Times: array([ 0.,  ...2.,  3.,  4.]), Values: array([ 0.,  ...2.,  3.,  4.]))

In [44]:
ts2 = ts*5

In [45]:
ts2 = smts.from_ops(ts*5)

In [46]:
ts2.times()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [47]:
ts._sm

FileStorageManager(1 ids: [12])

In [48]:
sm2 = StorageManager.FileStorageManager()

In [49]:
sm2.reload_index()

In [50]:
sm2

FileStorageManager(1 ids: [1])

In [51]:
sm.reload_index()

In [52]:
sm

FileStorageManager(1 ids: [1])

In [53]:
sm2.store(2,ts)

ArrayTimeSeries(Length: 10, Times: array([ 0.,  ...7.,  8.,  9.]), Values: array([ 0.,  ...7.,  8.,  9.]))

In [54]:
sm2, sm

(FileStorageManager(2 ids: [1, 2]), FileStorageManager(1 ids: [1]))

In [55]:
sm.reload_index()

In [56]:
sm2, sm

(FileStorageManager(2 ids: [1, 2]), FileStorageManager(2 ids: [1, 2]))

In [19]:
a = smts.from_db(sm,12)

In [20]:
a

SMTimeSeries(Length: 10, Times: array([ 0.,  ...7.,  8.,  9.]), Values: array([ 0.,  ...7.,  8.,  9.]))

In [22]:
sm._index

{1: (10, './FSM_filestorage/ts_1.npy'),
 12: (10, './FSM_filestorage/ts_12.npy')}

In [26]:
ts = smts(range(21),range(21),SM=sm)

In [27]:
ts.id

67

In [24]:
a[2]=None

In [34]:
a[2] in [None,np.nan]

False

In [45]:
a._times.dtype

dtype('int32')

In [50]:
np.issubdtype(a._values.dtype,np.float)

True

In [44]:
help(np.issubdtype)

Help on function issubdtype in module numpy.core.numerictypes:

issubdtype(arg1, arg2)
    Returns True if first argument is a typecode lower/equal in type hierarchy.
    
    Parameters
    ----------
    arg1, arg2 : dtype_like
        dtype or string representing a typecode.
    
    Returns
    -------
    out : bool
    
    See Also
    --------
    issubsctype, issubclass_
    numpy.core.numerictypes : Overview of numpy type hierarchy.
    
    Examples
    --------
    >>> np.issubdtype('S1', str)
    True
    >>> np.issubdtype(np.float64, np.float32)
    False



In [51]:
np.array([_ for _ in 'efgh'],dtype='float')

ValueError: could not convert string to float: 'e'

In [32]:
None in [None,np.nan]

True

In [59]:
sm = StorageManager.FileStorageManager()
a = np.arange(20).reshape(-1,2)
b = ats(a[:,0],a[:,1])
sm.store(100,b)
sm.store(101,b)

ArrayTimeSeries(Length: 10, Times: array([  0., ...,  16.,  18.]), Values: array([  1., ...,  17.,  19.]))

In [60]:
for i in range(100):
    sm.store(None,b)

In [62]:
_,fname = sm._index[100]
fname

'./FSM_filestorage/ts_100.npy'

In [23]:
os.rmdir('../temp_filestorage')

OSError: [WinError 145] The directory is not empty: '../temp_filestorage'

'./filestorage'

In [34]:
dir = '.'+sm._dir
if os.path.exists(dir):
    [ os.remove(dir+'/'+f) for f in os.listdir(dir) ]
    os.rmdir(dir)

In [25]:
!ls ../temp_filestorage

index.p


In [30]:
sm

FileStorageManager(503 ids: [9, 21, 30, 31, 37, ...])

In [21]:
for _ in range(20):
    sm2 = StorageManager.FileStorageManager()
    ts = smts(range(10,14),range(0,4),id=1,SM=sm2)

In [22]:
os.rmdir()

index.p


In [218]:
a = smts(b.times(),b.values(),12)

In [228]:
c = a.interpolate([1,2])

In [229]:
c._sm

FileStorageManager(4 ids: [12, 47, 88, 130])

In [230]:
a._sm

FileStorageManager(4 ids: [12, 47, 88, 130])

In [233]:
a.values()

array([  1.,   3.,   5.,   7.,   9.,  11.,  13.,  15.,  17.,  19.])

In [104]:
r.repr(list(range(20)))

'[0, 1, 2, 3, 4, ...]'

In [135]:
a = sm._index.copy()

In [146]:
a2 = list(a.keys())
a2.sort()
a2

[18,
 46,
 66,
 82,
 85,
 100,
 101,
 134,
 136,
 185,
 208,
 358,
 640,
 710,
 721,
 806,
 1075]

In [91]:
[z.keys()]

[dict_keys([])]

In [81]:
sm2._idx_file

'./filestorage/index.p'

In [77]:
with open(sm2._idx_file,'rb') as f:
    z = pickle.load(f)

In [82]:
sm2.reload_index()
sm2._index

{100: (10, './filestorage/ts_100.npy'), 101: (10, './filestorage/ts_101.npy')}

In [17]:
a = smts(b.times(),b.values(),12)

In [18]:
a._sm._index
a

SMTimeSeries(Length: 10, Times: array([  0., ...,  16.,  18.]), Values: array([  1., ...,  17.,  19.]))

In [19]:
a.times()

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.])

In [20]:
type(b)

ArrayTimeSeries.ArrayTimeSeries

In [40]:
c = StorageManager.SMTimeSeries.from_ts(b,SM=sm)

In [41]:
c._sm._index,c.id

({100: (10, './filestorage/ts_100.npy'),
  101: (10, './filestorage/ts_101.npy'),
  121: (10, './filestorage/ts_121.npy'),
  139: (10, './filestorage/ts_139.npy'),
  169: (10, './filestorage/ts_169.npy'),
  299: (10, './filestorage/ts_299.npy')},
 169)

In [24]:
c = StorageManager.SMTimeSeries.from_db(sm,100)

In [25]:
c._sm._index
c

SMTimeSeries(Length: 10, Times: array([  0., ...,  16.,  18.]), Values: array([  1., ...,  17.,  19.]))

In [275]:
d = smts(b.times(),b.values(),SM=sm)

In [276]:
d.id

260

In [277]:
sm._index

{11: (10, './filestorage/ts_11.npy'),
 100: (10, './filestorage/ts_100.npy'),
 101: (10, './filestorage/ts_101.npy'),
 204: (10, './filestorage/ts_204.npy'),
 260: (10, './filestorage/ts_260.npy'),
 380: (10, './filestorage/ts_380.npy')}

In [160]:
a = smts(SM=sm)

In [161]:
a._sm._index

{100: (10, './filestorage/ts_100.npy'), 101: (10, './filestorage/ts_101.npy')}

In [162]:
sm.store(102,b)
sm._index

{100: (10, './filestorage/ts_100.npy'),
 101: (10, './filestorage/ts_101.npy'),
 102: (10, './filestorage/ts_102.npy')}

In [163]:
a.from_db(100)

In [166]:
a

SMTimeSeries(Length: 10, Times: array([  0., ...,  16.,  18.]), Values: array([  1., ...,  17.,  19.]))

In [110]:
c = sm.get(100)
c

ArrayTimeSeries(Length: 10, Times: array([  0., ...,  16.,  18.]), Values: array([  1., ...,  17.,  19.]))

In [111]:
sm.size(100)

10

In [89]:
sm.size(10)

KeyError: 'There is no time series with id 10'

In [90]:
d = sm.get(10)

KeyError: 'There is no time series with id 10'

In [91]:
cls(a)
np.asarray()

NameError: name 'cls' is not defined

In [92]:
sm.store(100,b+10)

KeyError: 'There already a time series with id 100; if you want to overwrite, set overwrite=True'

In [93]:
e = sm.get(100)
e

ArrayTimeSeries(Length: 10, Times: array([  0., ...,  16.,  18.]), Values: array([  1., ...,  17.,  19.]))

In [94]:
directory = "./tempsave"
if not os.path.exists(directory):
    os.makedirs(directory)

In [17]:
a = np.ones((10,2))
a

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [18]:
np.save('./tempsave/a.npy',a)

    

In [19]:
b = np.load('./tempsave/a.npy')

In [20]:
b

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [21]:
a = dict()
a['pizza']='good'

In [22]:
a

{'pizza': 'good'}

In [23]:
'pizza' in a

True

In [24]:
a['bread']

KeyError: 'bread'

In [103]:
list(e.)

['_values', '_times']

In [112]:
smts()

TypeError: __init__() missing 2 required positional arguments: 'times' and 'values'

In [115]:
help(smts)

Help on class SMTimeSeries in module StorageManager:

class SMTimeSeries(timeSeriesABC.SizedContainerTimeSeriesInterface)
 |  own docstring here
 |  
 |  Method resolution order:
 |      SMTimeSeries
 |      timeSeriesABC.SizedContainerTimeSeriesInterface
 |      timeSeriesABC.TimeSeriesInterface
 |      abc.ABC
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__(self)
 |      Returns: L2-norm of the TimeSeries values
 |  
 |  __add__(self, rhs)
 |      Description
 |      -------------
 |      If rhs is Real, add it to all elements of `_values`.
 |      If rhs is a SizedContainerTimeSeriesInterface instance with the same
 |      times, add the values element-wise.
 |      
 |      Returns:
 |      --------
 |      A new TimeSeries instance with the same times but updated values
 |  
 |  __bool__(self)
 |      Returns: Returns True if all values in self._values are 
 |      zero. False, otherwise
 |  
 |  __eq__(self, rhs)
 |      Tests if two SizedContainerTimeSeri

In [49]:
z = dict()
for i in range(26):
    z[i]=i%3

In [51]:
import pickle

In [57]:
with open('./tempsave/pickle','wb') as f:
    pickle.dump(z,f)

In [58]:
!ls './tempsave/'

a.npy
pickle


In [60]:
with open('./tempsave/pickle','rb') as f:
    z2 = pickle.load(f)

In [62]:
z==z2

True

In [96]:
list(z2.keys())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [195]:
n = np.array([0,1,2,3,4])
np.sqrt((n**2).sum())

5.4772255750516612

In [194]:
np.linalg.norm(n)

5.4772255750516612

In [198]:
type(b.times())

numpy.ndarray

In [200]:
(b.times()==list(b.times())).all()

True

In [203]:
np.arange(10)+b

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [206]:
c+np.arange(10)

TypeError: unsupported operand type(s) for +: 'ArrayTimeSeries' and 'ndarray'

In [207]:
c = np.arange(0,4)
np.linalg.norm(c)

3.7416573867739413

In [208]:
b.__contains__(5)

True

In [209]:
b

ArrayTimeSeries(Length: 10, Times: array([ 0,  2..., 14, 16, 18]), Values: array([ 1,  3..., 15, 17, 19]))

In [210]:
ts = lts(range(0,4),range(10,14))

In [213]:
ts[2]

2

In [235]:
a_ = lts(range(4),range(5))

TypeError: Non sequence passed into constructor

In [240]:
h = smts(range(4),range(4))
h.interpolate([2])

SMTimeSeries(Length: 1, Times: array([ 2.]), Values: array([ 2.]))

In [243]:
i = ats(range(4),range(4))
i.interpolate([2])

ArrayTimeSeries(Length: 1, Times: array([2]), Values: array([2]))

In [249]:
j = lts(range(4),range(4))
j.interpolate([2,3])

TypeError: 'int' object is not iterable

In [250]:
t = 3
[v for v in t]

TypeError: 'int' object is not iterable